//ACCOUNT CREATED
export const ACCOUNT_ADDED_REQUEST = 'ACCOUNT_ADDED_REQUEST';
export const ACCOUNT_ADDED_SUCCESS = 'ACCOUNT_ADDED_SUCCESS';
export const ACCOUNT_ADDED_FAILURE = 'ACCOUNT_ADDED_FAILURE';