//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//ACCOUNT
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//ACCOUNT CREATED
export const ACCOUNT_ADDED_REQUEST = 'ACCOUNT_ADDED_REQUEST';
export const ACCOUNT_ADDED_SUCCESS = 'ACCOUNT_ADDED_SUCCESS';
export const ACCOUNT_ADDED_FAILURE = 'ACCOUNT_ADDED_FAILURE';